=== djaus2/ms-iot-community-samples-iis/ms-iot-community-samples-svc/FootWhatIf/games.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Games" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Games">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="ID" index-key="ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="/t+OZVV6G0uTz3eQ60mywQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAD+345lVXobS5PPd5DrSbLBAAAAANZOp2+1E+RAAAAAAAAAAABHAGEA
bQBlAHMAAAAAAAAAL04E71eIh0C1PVW732gmWwcAAAD+345lVXobS5PPd5DrSbLB
UgBvAHUAbgBkAAAAAAAAAF8booxyuFFPsF3VO9AJucMHAAAA/t+OZVV6G0uTz3eQ
60mywVQAZQBhAG0AMQAAAAAAAACrjV++AWHzT7Mnc3S8CCKfBwAAAP7fjmVVehtL
k893kOtJssFSAGUAcwB1AGwAdAAxAAAAAAAAAKd4meCz0CRKls0Xe/pxeekHAAAA
/t+OZVV6G0uTz3eQ60mywVMAYwBvAHIAZQAxAAAAAAAAACU0KdkjPHFAiJd686mm
LiQHAAAA/t+OZVV6G0uTz3eQ60mywVQAZQBhAG0AMgAAAAAAAADnN+RglPtESrwD
AgH4LpHgBwAAAP7fjmVVehtLk893kOtJssFSAGUAcwB1AGwAdAAyAAAAAAAAAKLq
MFI3s05Bn2bxSwPQvbsHAAAA/t+OZVV6G0uTz3eQ60mywVMAYwBvAHIAZQAyAAAA
AAAAAFok9dFTsZdAmG0b5zsVtEUHAAAA/t+OZVV6G0uTz3eQ60mywUgAbwBtAGUA
VABlAGEAbQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAA
AAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Round" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="L04E71eIh0C1PVW732gmWw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Team1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="XxuijHK4UU+wXdU70Am5ww==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Result1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="q41fvgFh80+zJ3N0vAginw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Score1" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="p3iZ4LPQJEqWzRd7+nF56Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Team2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="JTQp2SM8cUCIl3rzqaYuJA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Result2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="5zfkYJT7REq8AwIB+C6R4A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Score2" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ouowUjezTkGfZvFLA9C9uw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HomeTeam" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="WiT10VOxl0CYbRvnOxW0RQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== djaus2/ms-iot-community-samples-iis/ms-iot-community-samples-svc/FootWhatIf/round3.xml
<?xml version="1.0"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Games.xsd" generated="2012-07-27T16:05:18">
  <Games>
    <ID>204</ID>
    <Round>22</Round>
    <Team1>Richmond</Team1>
    <Result1>WIN</Result1>
    <Score1>13.24 (102)</Score1>
    <Team2>Essendon</Team2>
    <Result2>LOSS</Result2>
    <Score2>8.9 (57)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>205</ID>
    <Round>22</Round>
    <Team1>St Kilda</Team1>
    <Result1>WIN</Result1>
    <Score1>25.13 (163)</Score1>
    <Team2>Greater Western Sydney</Team2>
    <Result2>LOSS</Result2>
    <Score2>5.5 (35)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>203</ID>
    <Round>22</Round>
    <Team1>Port Adelaide</Team1>
    <Result1>LOSS</Result1>
    <Score1>14.9 (93)</Score1>
    <Team2>Brisbane</Team2>
    <Result2>WIN</Result2>
    <Score2>16.8 (104)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>206</ID>
    <Round>22</Round>
    <Team1>Sydney</Team1>
    <Result1>LOSS</Result1>
    <Score1>14.11 (95)</Score1>
    <Team2>Hawthorn</Team2>
    <Result2>WIN</Result2>
    <Score2>15.12 (102)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>200</ID>
    <Round>22</Round>
    <Team1>Gold Coast</Team1>
    <Result1>WIN</Result1>
    <Score1>15.8 (98)</Score1>
    <Team2>Carlton</Team2>
    <Result2>LOSS</Result2>
    <Score2>11.20 (86)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>207</ID>
    <Round>22</Round>
    <Team1>West Coast</Team1>
    <Result1>WIN</Result1>
    <Score1>15.17 (107)</Score1>
    <Team2>Collingwood</Team2>
    <Result2>LOSS</Result2>
    <Score2>8.10 (58)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>199</ID>
    <Round>22</Round>
    <Team1>Geelong</Team1>
    <Result1>WIN</Result1>
    <Score1>16.11 (107)</Score1>
    <Team2>Western Bulldogs</Team2>
    <Result2>LOSS</Result2>
    <Score2>11.7 (73)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>202</ID>
    <Round>22</Round>
    <Team1>North Melbourne</Team1>
    <Result1 />
    <Score1>12.7 (79)</Score1>
    <Team2>Fremantle</Team2>
    <Result2 />
    <Score2>20.12 (132)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>201</ID>
    <Round>22</Round>
    <Team1>Melbourne</Team1>
    <Result1 />
    <Score1 />
    <Team2>Adelaide</Team2>
    <Result2 />
    <Score2 />
    <HomeTeam>1</HomeTeam>
  </Games>
</dataroot>

=== djaus2/ms-iot-community-samples-iis/ms-iot-community-samples-svc/FootWhatIf/137Round20.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="games.xsd" generated="2012-08-18T23:19:00">
<Games>
<ID>181</ID>
<Round>20</Round>
<Team1>Adelaide</Team1>
<Result1>WIN</Result1>
<Score1>17.17 (119)</Score1>
<Team2>Fremantle</Team2>
<Result2>LOSS</Result2>
<Score2>14.7 (91)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>182</ID>
<Round>20</Round>
<Team1>Carlton</Team1>
<Result1>WIN</Result1>
<Score1>14.20 (104)</Score1>
<Team2>Brisbane</Team2>
<Result2>LOSS</Result2>
<Score2>13.6 (84)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>183</ID>
<Round>20</Round>
<Team1>Essendon</Team1>
<Result1>LOSS</Result1>
<Score1>11.10 (76)</Score1>
<Team2>North Melbourne</Team2>
<Result2>WIN</Result2>
<Score2>15.10 (100)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>184</ID>
<Round>20</Round>
<Team1>Gold Coast</Team1>
<Result1>WIN</Result1>
<Score1>16.13 (109)</Score1>
<Team2>Greater Western Sydney</Team2>
<Result2>LOSS</Result2>
<Score2>12.7 (79)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>185</ID>
<Round>20</Round>
<Team1>Hawthorn</Team1>
<Result1>WIN</Result1>
<Score1>24.15 (159)</Score1>
<Team2>Port Adelaide</Team2>
<Result2>LOSS</Result2>
<Score2>13.9 (87)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>186</ID>
<Round>20</Round>
<Team1>Richmond</Team1>
<Result1>WIN</Result1>
<Score1>22.18 (150)</Score1>
<Team2>Western Bulldogs</Team2>
<Result2>LOSS</Result2>
<Score2>12.8 (80)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>187</ID>
<Round>20</Round>
<Team1>St Kilda</Team1>
<Result1>WIN</Result1>
<Score1>16.11 (107)</Score1>
<Team2>Melbourne</Team2>
<Result2>LOSS</Result2>
<Score2>12.10 (82)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>188</ID>
<Round>20</Round>
<Team1>Sydney</Team1>
<Result1>LOSS</Result1>
<Score1>9.16 (70)</Score1>
<Team2>Collingwood</Team2>
<Result2>WIN</Result2>
<Score2>12.6 (78)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>189</ID>
<Round>20</Round>
<Team1>West Coast</Team1>
<Result1>WIN</Result1>
<Score1>16.6 (102)</Score1>
<Team2>Geelong</Team2>
<Result2>LOSS</Result2>
<Score2>15.7 (97)
6.12 (48)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
</dataroot>

=== djaus2/ms-iot-community-samples-iis/ms-iot-community-samples-svc/FootWhatIf/137Round23.xml
<?xml version="1.0"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Games.xsd" generated="2012-07-27T16:05:18">
  <Games>
    <ID>215</ID>
    <Round>23</Round>
    <Team1>Hawthorn</Team1>
    <Result1>WIN</Result1>
    <Score1>14.11 (95)</Score1>
    <Team2>West Coast</Team2>
    <Result2>LOSS</Result2>
    <Score2>10.10 (70)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>213</ID>
    <Round>23</Round>
    <Team1>Geelong</Team1>
    <Result1>WIN</Result1>
    <Score1>17.10 (112)</Score1>
    <Team2>Sydney</Team2>
    <Result2>LOSS</Result2>
    <Score2>11.12 (78)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>208</ID>
    <Round>23</Round>
    <Team1>Adelaide</Team1>
    <Result1>WIN</Result1>
    <Score1>22.21 (153)</Score1>
    <Team2>Gold Coast</Team2>
    <Result2>LOSS</Result2>
    <Score2>9.8 (62)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>214</ID>
    <Round>23</Round>
    <Team1>Greater Western Sydney</Team1>
    <Result1>LOSS</Result1>
    <Score1>11.11 (77)</Score1>
    <Team2>North Melbourne</Team2>
    <Result2>WIN</Result2>
    <Score2>16.9 (105)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>212</ID>
    <Round>23</Round>
    <Team1>Fremantle</Team1>
    <Result1>WIN</Result1>
    <Score1>14.17 (101)</Score1>
    <Team2>Melbourne</Team2>
    <Result2>LOSS</Result2>
    <Score2>5.10 (40)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>211</ID>
    <Round>23</Round>
    <Team1>Essendon</Team1>
    <Result1>LOSS</Result1>
    <Score1>10.12 (72)</Score1>
    <Team2>Collingwood</Team2>
    <Result2>WIN</Result2>
    <Score2>14.20 (104)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>210</ID>
    <Round>23</Round>
    <Team1>Carlton</Team1>
    <Result1>LOSS</Result1>
    <Score1>12.19 (91)</Score1>
    <Team2>St Kilda</Team2>
    <Result2>WIN</Result2>
    <Score2>16.10 (106)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>216</ID>
    <Round>23</Round>
    <Team1>Richmond</Team1>
    <Result1>DRAW</Result1>
    <Score1>16.10 (106)</Score1>
    <Team2>Port Adelaide</Team2>
    <Result2>DRAW</Result2>
    <Score2>16.10 (106)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
  <Games>
    <ID>209</ID>
    <Round>23</Round>
    <Team1>Brisbane</Team1>
    <Result1>WIN</Result1>
    <Score1>19.14 (128)</Score1>
    <Team2>Western Bulldogs</Team2>
    <Result2>LOSS</Result2>
    <Score2>9.7 (61)</Score2>
    <HomeTeam>1</HomeTeam>
  </Games>
</dataroot>

=== djaus2/ms-iot-community-samples-iis/ms-iot-community-samples-svc/FootWhatIf/137Round21.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Games.xsd" generated="2012-07-27T16:05:18">
<Games>
<ID>190</ID>
<Round>21</Round>
<Team1>Brisbane</Team1>
  <Result1>WIN</Result1>
  <Score1>13.17 (95)</Score1>
<Team2>Adelaide</Team2>
  <Result2>LOSS</Result2>
  <Score2>12.13 (85)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>191</ID>
<Round>21</Round>
<Team1>Collingwood</Team1>
  <Result1>LOSS</Result1>
  <Score1>8.13 (61)</Score1>
<Team2>North Melbourne</Team2>
  <Result2>WIN</Result2>
  <Score2>13.13 (91)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>192</ID>
<Round>21</Round>
<Team1>Essendon</Team1>
  <Result1>LOSS</Result1>
  <Score1>8.12 (60)</Score1>
<Team2>Carlton</Team2>
  <Result2>WIN</Result2>
  <Score2>24.12 (156)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>193</ID>
<Round>21</Round>
<Team1>Fremantle</Team1>
  <Result1>WIN</Result1>
  <Score1>13.16 (94)</Score1>
<Team2>Richmond</Team2>
  <Result2>LOSS</Result2>
  <Score2>11.6 (72)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>194</ID>
<Round>21</Round>
<Team1>Geelong</Team1>
  <Result1>WIN</Result1>
  <Score1>18.15 (123)</Score1>
<Team2>St Kilda</Team2>
  <Result2>LOSS</Result2>
  <Score2>11.15 (81)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>195</ID>
<Round>21</Round>
<Team1>Greater Western Sydney</Team1>
  <Result1>LOSS</Result1>
  <Score1>9.5 (59)</Score1>
<Team2>Melbourne</Team2>
  <Result2>WIN</Result2>
  <Score2>11.18 (84)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>196</ID>
<Round>21</Round>
<Team1>Hawthorn</Team1>
  <Result1>WIN</Result1>
  <Score1>19.15 (129)</Score1>
<Team2>Gold Coast</Team2>
  <Result2>LOSS</Result2>
  <Score2>10.5 (65)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>197</ID>
<Round>21</Round>
<Team1>Port Adelaide</Team1>
  <Result1>LOSS</Result1>
  <Score1>6.14 (50)</Score1>
<Team2>West Coast</Team2>
  <Result2>WIN</Result2>
  <Score2>14.14 (98)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
<Games>
<ID>198</ID>
<Round>21</Round>
<Team1>Western Bulldogs</Team1>
  <Result1>LOSS</Result1>
  <Score1>13.7 (85)</Score1>
<Team2>Sydney</Team2>
  <Result2>WIN</Result2>
  <Score2>26.11 (167)</Score2>
<HomeTeam>1</HomeTeam>
</Games>
</dataroot>
